# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Added from New Projects

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - script: echo Job1 - Hello, world, Changed!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Job2!
    displayName: 'Job2 - a one-line script'
- job: Job3
  dependsOn: Job2
  steps:
  - script: echo Job3!
    displayName: 'Job3 - a one-line script'
- job: Job4
  dependsOn:
  - Job2
  - Job3
  steps:
  - script: echo Job4!
    displayName: 'Job4 - a one-line script'

