#02-Stages

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  variables:
   stage_var: Build
  jobs:
  - job: FirstJob
    steps:
    # - bash: echo Build FirstJob and stage varaible $(stage_var)
    # - bash: echo Build FirstJob
    # - bash: echo $(PipelineLevelVariable)
    # - bash: echo $(Build.BuildNumber)
    # - bash: echo $(Build.BuildId)
    # - bash: echo $(Build.SourceBranchName)
    # - bash: echo $(Build.SourcesDirectory)
    # - bash: java -version
    # - bash: node --version
    # - bash: python --version 
    # - bash: mvn -version 
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
  # - job: SecoundJob
  #   steps:
  #   - bash: echo Build SecoundJob and PLvariable $(PipelineLevelVariable)
############################################
# - stage: DevDeploy
#   variables:
#    stage_var: Dev
#   dependsOn: Build
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - bash: echo $(stage_var)_DeployJob
############################################
# - stage: QADeploy
#   dependsOn: Build
#   jobs:
#   - job: QADeployJob
#     steps:
#       - bash: echo QADeployJob
############################################
# - stage: ProdDeploy
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - bash: echo ProdDeploy