trigger:
- main

strategy:
 matrix:
   linux:
     operatingsystem: ubuntu-latest
   mac:
     operatingsystem: macos-latest

pool:
  vmImage: $(operatingsystem)

steps:
- script: echo "runningin OS $(operatingsystem)"
  displayName: 'Run a one-line script'
